
install-golangci-lint:
    desc: install golangci-lint binary
    cmds:
      - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1

lint:
    desc: executes golangci-lint which is a linters aggregator
    deps: [header]
    cmds:
      - $(go env GOPATH)/bin/golangci-lint run ./...

